### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by Programmerino** [klokare/evo#3]
When using go get for this project, I get error:
```
package github.com/klokare/evo/example/boxes: cannot find package "github.com/klokare/evo/example/boxes" in any of:
	/usr/lib/golang/src/github.com/klokare/evo/example/boxes (from $GOROOT)
	/home/davis/go/src/github.com/klokare/evo/example/boxes (from $GOPATH)
```

**Comment by klokare** [comment]
The boxes example should not have been referenced yet in the git repository but it appears to have been. Sorry about that. I committed many changes today, including adding the boxes experiment, so this problem should be fixed. I tried a fresh `go get`from my linux box and all seems well. NOTE: you do need mercurial installed (see the updated README.md) in addition to git as some of the gonum/plot dependencies use it as the source control version.
