### ISSUE TITLE
injectable searcher implementations

### ISSUE THREAD

**Issue by kpacha** [klokare/evo#7]
Hi!

First of all, kudos for the lib. It's awesome!!!

The current implementation of the `neat.Experiment` defines the searcher by the implementation instead of by the interface, so clients can not use their own implementations and, depending on the requirements of the experiment, that's a problem. In my case, I'm trying to evaluate all the phenomes of a given generation at once using the same evaluator.

it would be nice to also add an implementation of such searcher and evaluator to this awesome package.

Cheers!

**Comment by klokare** [comment]
Hey. Thanks for trying things out and for catching this. The intent is, as you say, to have neat.Experiment be interface driven so that you can use your own implementations. I see your pull request and will integrate it now.  (I should also fix the the forward.Translator -> interface, too).

**Comment by kpacha** [comment]
wow, that was quick!

thxs
